export const API = {
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGIN: '/auth/login',
  AUTH_ME: '/auth/me',
  AUTH_FORGOT: '/auth/forgot-password',
  AUTH_RESET: '/auth/reset-password',
  AUTH_CHANGE_PASSWORD: '/auth/change-password',
  USERS: '/users',
  USER_BY_ID: (id) => `/users/${id}`,
  CATEGORIES: '/categories',
  CATEGORY_BY_SLUG: (slug) => `/categories/${slug}`,
  PRODUCTS: '/products',
  PRODUCT_BY_SLUG: (slug) => `/products/${slug}`,
  CART: '/cart',
  CART_ITEMS: '/cart/items',
  CART_ITEM: (productId) => `/cart/items/${productId}`,
  ORDERS: '/orders',
  ORDER_BY_ID: (id) => `/orders/${id}`,
  ORDER_STATUS: (id) => `/orders/${id}/status`,
  UPLOAD: '/upload',
  WISHLIST: '/wishlist',
  WISHLIST_TOGGLE: '/wishlist/toggle',
  REVIEWS_BY_PRODUCT: (slug) => `/reviews/product/${slug}`,
  REVIEW_CREATE: (slug) => `/reviews/product/${slug}`,
  PRODUCT_RELATED: (slug) => `/products/${slug}/related`,
  PRODUCT_BRANDS: '/products/meta/brands',
  ADMIN_STATS: '/admin/stats',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_USERS: '/admin/users',
  COUPONS: '/coupons',
  COUPON_VALIDATE: '/coupons/validate',
  COUPON_BY_ID: (id) => `/coupons/${id}`,
};
