export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/san-pham',
  PRODUCT_DETAIL: '/san-pham/:slug',
  CATEGORY: '/danh-muc/:slug',
  SEARCH: '/tim-kiem',
  CART: '/gio-hang',
  CHECKOUT: '/thanh-toan',
  LOGIN: '/dang-nhap',
  REGISTER: '/dang-ky',
  FORGOT_PASSWORD: '/quen-mat-khau',
  RESET_PASSWORD: '/dat-lai-mat-khau',
  PROFILE: '/tai-khoan',
  ORDERS: '/don-hang',
  ORDER_DETAIL: '/don-hang/:id',
  WISHLIST: '/yeu-thich',
  COMPARE: '/so-sanh',
  ADMIN: '/admin',
};
