services:
  mongo:
    image: mongo:7
    container_name: didongviet-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - didongviet_mongo_data:/data/db

volumes:
  didongviet_mongo_data:
